### ISSUE TITLE
iOS加载sf2失败

### ISSUE THREAD

**Issue by yk81708090** [santoxyz/flutter_midiplayer#1]
iOS加载sf2无法播出声音，请问如何解决？

**Comment by santoxyz** [comment]
lib searches and loads soundfont 
        let bankURL = documentDirectory?.appendingPathComponent("soundfont_GM.sf2")

feel free to modify it according to your needs.

**Comment by yk81708090** [comment]
谢谢，我是修改了代码，1.安卓增加CLEAN， 否则每次进去加载会出现音频一直加载占用内存。
2.苹果端START中有对声音的设置，我们在测试发现，这段代码影响播放。注释掉。
3.速率设置load需要增加初始化，
4.我在内部增加了释放的逻辑，因为退出即需要释放，再进来重新load。

**Comment by santoxyz** [comment]
If you have it done, please PR.

**Comment by yk81708090** [comment]
swift:
let bankURL = documentDirectory?.appendingPathComponent("soundfont_GM.sf2")
soundfont_GM.sf2文件需要copy到Resources下，

如果使用assets下的sf2音色库，可以在dart中使用如下code：

Future copyFromAssets() async {
    //copy soundfont to Documents
    String name = "Piano.sf2";// 音色库文件名称
    var content = await rootBundle.load('assets/$name');
    Directory appDocDir = await getApplicationDocumentsDirectory();
    File newFile = File('${appDocDir.path}/$name');
    if (!await newFile.exists()) {
      newFile.writeAsBytesSync(content.buffer.asUint8List());
    }
  }
